spring.application.name=futbol-apirest

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://ngqwrld_db_user:3fhvNQ54UBHIwMVI@clubesdb.ijc0dpk.mongodb.net/futbol_db

# Evitar error de serialización circular con @DocumentReference
spring.jackson.serialization.fail-on-empty-beans=false
