spring.application.name=futbol-apirest

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}

# Evitar error de serialización circular con @DocumentReference
spring.jackson.serialization.fail-on-empty-beans=false